// Generated by CoffeeScript 1.8.0
(function() {
  var DS, StormForgeAsset,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  DS = require('../stormforge');

  StormForgeAsset = (function(_super) {
    __extends(StormForgeAsset, _super);

    function StormForgeAsset() {
      return StormForgeAsset.__super__.constructor.apply(this, arguments);
    }

    StormForgeAsset.prototype.name = 'asset';

    StormForgeAsset.prototype.schema = {
      resource: DS.belongsTo('resource', {
        required: true
      }),
      instance: DS.attr('uuid', {
        required: true
      }),
      isActive: DS.attr('boolean', {
        defaultValue: false
      }),
      ipAddress: DS.attr('string'),
      agent: DS.attr('string', {
        external: true
      })
    };

    return StormForgeAsset;

  })(DS.Model);

  module.exports = StormForgeAsset;

}).call(this);
