// Generated by CoffeeScript 1.8.0
(function() {
  var compiler, output, path, schema, schemas;

  path = require('path');

  schemas = path.resolve(__dirname, '../schemas');

  compiler = require('yang-compiler');

  compiler.merge(require('yang-storm'));

  schema = (require('fs')).readFileSync(path.join(schemas, 'stormforge.yang'), 'utf-8');

  output = compiler.compile(schema, {
    sourcedir: schemas
  });

  module.exports = output;

}).call(this);
