// Generated by CoffeeScript 1.8.0
(function() {
  var compiler, output, schema;

  compiler = require('yang-storm');

  schema = (require('fs')).readFileSync("" + __dirname + "/../schemas/stormforge.yang", 'utf-8');

  output = compiler.compile(schema);

  module.exports = output;

}).call(this);
