# the following config is used when ENV is as follows:
# NODE_ENV=intercloud
# NODE_APP_INSTANCE=vhub4

openstack:
  auth:
    url: http://vhub4.intercloud.net:5000/v2.0
    tenant:
      id: 62a2d90992114994977fd6707bac5758
    credentials:
      username: peter
      password: # set OS_PASSWORD=xxxx environmental variable

opnfv-promise:
  promise:
    policy:
      reservation:
        max-future-start-range: 7
        max-duration: 24
